---
- name: Install Docker
  hosts: backend
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Enable Docker service on boot
      service:
        name: docker
        enabled: yes

- name: Manage Laravel Docker container
  hosts: backend
  become: yes
  tasks:
    - name: Pull Laravel Docker image
      community.docker.docker_image:
        name: ayaomer/laravel-app
        tag: latest
        source: pull

    - name: Stop existing Laravel container if it exists
      community.docker.docker_container:
        name: laravel-backend
        state: stopped
      ignore_errors: yes  # Ignore errors if the container does not exist

    - name: Remove existing Laravel container if it exists
      community.docker.docker_container:
        name: laravel-backend
        state: absent
      ignore_errors: yes  # Ignore errors if the container does not exist

    - name: Run Laravel Docker container
      community.docker.docker_container:
        name: laravel-backend
        image: ayaomer/laravel-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "5000:80"
        env:
          DB_CONNECTION: mysql
          DB_HOST: "{{ db_endpoint }}"
          DB_PORT: "3306"
          DB_DATABASE: "mydb"
          DB_USERNAME: "admin"
          DB_PASSWORD: "12345678"
